fix(steps/azure-get-secrets): fix yaml formatting

diff --git a/steps/azure_get_secrets.yml b/steps/azure_get_secrets.yml
--- a/steps/azure_get_secrets.yml
+++ b/steps/azure_get_secrets.yml
@@ -10,17 +10,17 @@ parameters:
     default: []
 
 steps:
-- ${{ each secret in parameters.secrets }}:
-  - script: |
-      echo "Retrieving secret ${{ secret.name }}..."
-      SECRET_JSON=$(az keyvault secret show -n ${{ secret.name }} --vault-name ${{ parameters.keyVaultName }}; exit $?)
+  - ${{ each secret in parameters.secrets }}:
+    - script: |
+        echo "Retrieving secret ${{ secret.name }}..."
+        SECRET_JSON=$(az keyvault secret show -n ${{ secret.name }} --vault-name ${{ parameters.keyVaultName }}; exit $?)
 
-      if [[ $? -ne 0 ]]; then
-        echo "##vso[task.logissue type=error]Could not retrieve secret: ${{ secret.name }}."
-        exit 1
-      else
-      
-      SECRET_VALUE=$(echo "$SECRET_JSON" | jq -c -r '.value')
-      echo "##vso[task.setvariable variable=${{ secret.variable }};issecret=true]$SECRET_VALUE"
-      echo "Secret now available as variable: ${{ secret.variable }}"
-    displayName: Retrieve ${{ secret.name }} secret from Key Vault 
+        if [[ $? -ne 0 ]]; then
+          echo "##vso[task.logissue type=error]Could not retrieve secret: ${{ secret.name }}."
+          exit 1
+        else
+        
+        SECRET_VALUE=$(echo "$SECRET_JSON" | jq -c -r '.value')
+        echo "##vso[task.setvariable variable=${{ secret.variable }};issecret=true]$SECRET_VALUE"
+        echo "Secret now available as variable: ${{ secret.variable }}"
+      displayName: Retrieve ${{ secret.name }} secret from Key Vault 
