fix(templates): error handling
Add additional error handling in scripts to ensure pipeline exits with an error.

diff --git a/steps/azure_get_secrets.yml b/steps/azure_get_secrets.yml
--- a/steps/azure_get_secrets.yml
+++ b/steps/azure_get_secrets.yml
@@ -13,7 +13,14 @@ steps:
 - ${{ each secret in parameters.secrets }}:
   - script: |
       echo "Retrieving secret ${{ secret.name }}..."
-      SECRET_VALUE=$(az keyvault secret show -n ${{ secret.name }} --vault-name ${{ parameters.keyVaultName }} | jq -c -r '.value')
+      SECRET_JSON=$(az keyvault secret show -n ${{ secret.name }} --vault-name ${{ parameters.keyVaultName }}; exit $?)
+
+      if [[ $? -ne 0 ]]; then
+        echo "##vso[task.logissue type=error]Could not retrieve secret: ${{ secret.name }}."
+        exit 1
+      else
+      
+      SECRET_VALUE=$(echo "$SECRET_JSON" | jq -c -r '.value')
       echo "##vso[task.setvariable variable=${{ secret.variable }};issecret=true]$SECRET_VALUE"
       echo "Secret now available as variable: ${{ secret.variable }}"
     displayName: Retrieve ${{ secret.name }} secret from Key Vault 
